{
    'name': 'Sotral Transportation Management',
    'summary': """Buses, Bus stops, Bus lines, Cards, Payement, Control ...""",
    'version': '0.1.0',
    'description': """Buses, Bus stops, Bus lines, Cards, Payement, Control ...""",
    'author': 'Mawaba Botossi',
    'company': 'CrucialDigital',
    'website': 'http://www.crucialsa.com',
    'category': 'Tools',
    'depends': ['base'],
    'license': 'AGPL-3',
    'depends': ['fleet', 'hr'],
    'data': [
        'views/strl_menu.xml',
        'views/strl_bus.xml',
        'views/strl_bus_transportations.xml',
        'views/hr_employee.xml',
        'views/card_transactions.xml',
    ],
    'demo': [],
    "application": True,
    'installable': True,
    'auto_install': False,
}
